<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>GadecLogo.png</PackageIcon>
	</PropertyGroup>
	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="" />
		<None Include="GadecLogo.png" Pack="true" PackagePath=""/>
	</ItemGroup>
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<OutputType>Library</OutputType>
		<StartupObject>
		</StartupObject>
		<RootNamespace>Gadec</RootNamespace>
		<AssemblyName>GadecCommonLibraryCore</AssemblyName>
		<MyType>Windows</MyType>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<UseWindowsForms>true</UseWindowsForms>
		<UseWPF>true</UseWPF>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
		<AssemblyTitle>Gadec Common Library</AssemblyTitle>
		<Description>Has all de common extensionmethodes and functions voor Gadec software.</Description>
		<Company>Gadec Engineerings Software</Company>
		<Product>Gadec Common Library Core</Product>
		<Copyright>Gadec Engineerings Software ©  2025</Copyright>
		<AssemblyVersion>3.0.0.0</AssemblyVersion>
		<FileVersion>3.0.0.0</FileVersion>
		<Version>1.4.0</Version>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<DocumentationFile>GadecCommonLibrary.xml</DocumentationFile>
		<NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<DefineDebug>false</DefineDebug>
		<DocumentationFile>GadecCommonLibrary.xml</DocumentationFile>
		<NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
	</PropertyGroup>
	<ItemGroup>
		<Import Include="System.Drawing" />
		<Import Include="System.Windows.Forms" />
	</ItemGroup>
	<ItemGroup>
		<Compile Update="Dialogs\WaitUntilDialog.designer.vb">
			<DependentUpon>WaitUntilDialog.vb</DependentUpon>
		</Compile>
		<Compile Update="Dialogs\HistoryDialog.Designer.vb">
			<DependentUpon>HistoryDialog.vb</DependentUpon>
		</Compile>
		<Compile Update="Dialogs\ExceptionDialog.Designer.vb">
			<DependentUpon>ExceptionDialog.vb</DependentUpon>
		</Compile>
		<Compile Update="My Project\Application.Designer.vb">
			<AutoGen>True</AutoGen>
			<DependentUpon>Application.myapp</DependentUpon>
			<DesignTime>True</DesignTime>
		</Compile>
		<Compile Update="My Project\Resources.Designer.vb">
			<AutoGen>True</AutoGen>
			<DesignTime>True</DesignTime>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
		<Compile Update="My Project\Settings.Designer.vb">
			<AutoGen>True</AutoGen>
			<DependentUpon>Settings.settings</DependentUpon>
			<DesignTimeSharedInput>True</DesignTimeSharedInput>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<None Update="My Project\Application.myapp">
			<Generator>MyApplicationCodeGenerator</Generator>
			<LastGenOutput>Application.Designer.vb</LastGenOutput>
		</None>
	</ItemGroup>
	<ItemGroup>
		<Service Include="{508349B6-6B84-4DF5-91F0-309BEEBAD82D}" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
	</ItemGroup>
</Project>